name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          npm run dev
        env:
          JUNO_TOKEN: nrimk-7i5iw-gbygo-y7qo2-ytp4p-h4266-6wz67-4rwd3-flmih-2vuaz-oqe
